install: add more test and echo

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,9 +1,13 @@
 #!/usr/bin/env sh
 
-set -eu
+set -u
+
+type curl > /dev/null || { echo "curl: not found"; exit 1; }
+
+set -e
 
 get_latest_release() {
-  repo="$1"
+  local repo="$1"
 	curl -sSL "https://api.github.com/repos/${repo}/releases/latest" | \
     awk 'BEGIN{FS=": |,|\""}; /tag_name/{print $5}'
 }
@@ -16,17 +20,29 @@ package="gobackup-${platform}-${arch}.tar.gz"
 package_url="https://github.com/${repo}/releases/download/${version}/${package}"
 bin="gobackup"
 dest_dir="/usr/local/bin"
+bin_path="${dest_dir}/${bin}"
 tmp_dir="$(mktemp -d)"
 
 trap "rm -r ${tmp_dir}" EXIT
 
+if test -e "${bin_path}"; then
+  current_version="v$("${bin_path}" -v | awk '{print $NF}')"
+  if test "${current_version}" = "${version}"; then
+    echo "${bin} is already updated, no need to upgrade."
+    exit 0
+  else
+    echo "There is a new version of ${bin}, starting to upgrade from ${current_version} to ${version}."
+  fi
+fi
 cd "${tmp_dir}"
 curl -sSL "${package_url}" | tar xzf -
 
 if test $(id -u) -eq 0; then
-   mv "${bin}" "${dest_dir}"
+  mv "${bin}" "${dest_dir}"
 else
-   sudo mv "${bin}" "${dest_dir}"
+  sudo mv "${bin}" "${dest_dir}"
 fi
 
 mkdir -p ~/.gobackup
+
+echo "${bin} ${version} has been installed."
